### PR TITLE
Add npm publish workflow

### PR DESCRIPTION
**Pull request by Pytal**
From https://github.com/nextcloud/nextcloud-dialogs/blob/3d1848f9fdecd5e6d5ab927bd5c781a803762a45/.github/workflows/npm-publish.yml

### CODE REVIEW

**Comment by Pytal** [comment]
Would it make sense to also mirror the npm packages in https://github.com/nextcloud-releases as well?

**Comment by Pytal** [comment]
Would it make sense to mirror the npm packages in https://github.com/nextcloud-releases as well?

**Comment by skjnldsv** [comment]
> From [nextcloud/nextcloud-dialogs@`3d1848f`/.github/workflows/npm-publish.yml](https://github.com/nextcloud/nextcloud-dialogs/blob/3d1848f9fdecd5e6d5ab927bd5c781a803762a45/.github/workflows/npm-publish.yml)

Why not the one from the github template repo?

**Comment by ChristophWurst** [comment]
> Would it make sense to mirror the npm packages in https://github.com/nextcloud-releases as well?

If we need a secret token then yes, the workflow has to run somewhere with finer control

**Comment by Pytal** [comment]
> Why not the one from the github template repo? [nextcloud/nextcloud-typings/new/master?filename=.github%2Fworkflows%2Fnpm-publish.yml&workflow_template=npm-publish](https://github.com/nextcloud/nextcloud-typings/new/master?filename=.github%2Fworkflows%2Fnpm-publish.yml&workflow_template=npm-publish)

Just thought https://github.com/nextcloud/nextcloud-dialogs would have an up to date workflow but it wasn't https://github.com/nextcloud/nextcloud-dialogs/pull/408

> If we need a secret token then yes, the workflow has to run somewhere with finer control

Actually there is already a permission check https://github.com/nextcloud/nextcloud-typings/pull/142/files#diff-8a5ce8b612395836520d0655143f732d08e747af57f3cfe76b5e283600106240R18-R21 so I don't think it's necessary

Anyways, look good to approve now?

**Review by skjnldsv — APPROVED** [review]

**Comment by Pytal** [comment]
Could a repo admin add an `NPM_TOKEN` secret to this repo?

**Pull request merged**
